# Node docker image on which this would be run
image: node:latest

stages:
  - test

services:
  - mongo:latest
# Job 1:
Test:
  stage: test
  script:
    - apt-get update -qy
    - apt-get install -y nodejs
    - apt-get install -y ruby-dev
    - gem install dpl
    - npm start
    - dpl --provider=heroku --app=HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
    #- docker run -dti -p 27017:27017 --name mongodb mongo


    #Job 2:
#Deploy to staging
#Production:
#  image: mongo:latest
#  only:
#    - master
#  stage: deploy_production
#  script:
#    - gem install dpl
#    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
