# Node docker image on which this would be run
image: node:latest

stages:
  - test
  - deploy

services:
  - mongo:latest
# Job 1:
Test:
  stage: test
  script:
    - apt-get update -qy
    - apt-get install -y nodejs
    - apt-get install -y ruby-dev
    - npm start


    #Job 2:
#Deploy to staging
Production:
  only:
    - master
  stage: deploy
  script:
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
